"""Exploratory statistics behind docs/01-data.md and docs/hypotheses.md (`uv run poe eda`).

Computed on the training split only, unless a table is explicitly about time (daily CTR), so that
the hypotheses are not shaped by validation or test data.
"""

from pathlib import Path

import polars as pl

from charade.config import get_settings
from charade.data.load import load_joined
from charade.data.split import assign_split
from charade.features.counters import offline_counters
from charade.features.derive import PLACEHOLDER_DEVICE_ID, derive, user_proxy

OUT = Path("reports/eda")


def _table(frame: pl.DataFrame) -> str:
    header = "| " + " | ".join(frame.columns) + " |"
    rule = "|" + "---|" * frame.width
    rows = ["| " + " | ".join(_fmt(v) for v in row) + " |" for row in frame.iter_rows()]
    return "\n".join([header, rule, *rows])


def _fmt(value: object) -> str:
    if isinstance(value, float):
        return f"{value:.4f}"
    if isinstance(value, int):
        return f"{value:,}"
    return str(value)


def _ctr_by(frame: pl.DataFrame, by: str | pl.Expr) -> pl.DataFrame:
    return (
        frame.group_by(by)
        .agg(pl.len().alias("impressions"), pl.col("click").mean().alias("ctr"))
        .sort("impressions", descending=True)
    )


def _interaction(frame: pl.DataFrame, factor: str, top: int = 30, min_n: int = 300) -> pl.DataFrame:
    """Residual of cell CTR from the additive model (factor + campaign), against its binomial SE."""
    base = float(frame["click"].mean())  # pyright: ignore[reportArgumentType]
    campaigns = frame.group_by("C17").len().sort(["len", "C17"], descending=[True, False]).head(top)["C17"]
    sub = frame.filter(pl.col("C17").is_in(campaigns.implode()))
    f_rate = sub.group_by(factor).agg(pl.col("click").mean().alias("f"))
    c_rate = sub.group_by("C17").agg(pl.col("click").mean().alias("c"))
    cells = (
        sub.group_by([factor, "C17"])
        .agg(pl.len().alias("n"), pl.col("click").mean().alias("y"))
        .join(f_rate, on=factor)
        .join(c_rate, on="C17")
        .filter(pl.col("n") >= min_n)
        .with_columns(
            (pl.col("y") - pl.col("f") - pl.col("c") + base).alias("residual"),
            (pl.col("y") * (1 - pl.col("y")) / pl.col("n")).sqrt().alias("se"),
        )
    )
    return pl.DataFrame(
        {
            "factor": [factor],
            "cells": [cells.height],
            "residual_sd": [float(cells["residual"].std() or 0.0)],  # pyright: ignore[reportArgumentType]
            "mean_binomial_se": [float(cells["se"].mean() or 0.0)],  # pyright: ignore[reportArgumentType]
        }
    )


def run(data_dir: Path, out: Path = OUT) -> None:
    """Write reports/eda/*.md."""
    settings = get_settings()
    frame = assign_split(
        derive(offline_counters(load_joined(data_dir).with_columns(user_proxy()))), settings.train_end, settings.val_end
    )
    train = frame.filter(pl.col("split") == "train")
    same_hour = train.with_columns(pl.len().over(["user", "ts"]).clip(1, 6).alias("same_hour_user_imps"))
    repeat = train.with_columns(pl.int_range(pl.len()).over(["user", "C17"]).clip(0, 5).alias("prior_same_campaign"))
    sections = {
        "Daily CTR (all splits)": frame.group_by(pl.col("ts").dt.date().alias("day"), "split")
        .agg(pl.len().alias("impressions"), pl.col("click").mean().alias("ctr"))
        .sort("day"),
        "Genre": _ctr_by(train, "genre"),
        "Safety tier": _ctr_by(train, "safety_tier"),
        "Creator type": _ctr_by(train, "creator_type"),
        "Surface": _ctr_by(train, "surface"),
        "Banner position": _ctr_by(train, "banner_pos"),
        "Conversation turn": _ctr_by(train, "turn_bucket").sort("turn_bucket"),
        "Placeholder device_id share": train.select(
            (pl.col("device_id") == PLACEHOLDER_DEVICE_ID).mean().alias("share")
        ),
        "User seen before (strictly earlier hours)": _ctr_by(
            train, pl.col("user_imps").clip(0, 5).alias("prior_imps")
        ).sort("prior_imps"),
        "Same-hour user impressions (LEAK: unknown at serve time)": _ctr_by(same_hour, "same_hour_user_imps").sort(
            "same_hour_user_imps"
        ),
        "Prior exposures to the same campaign (row order within hour)": _ctr_by(repeat, "prior_same_campaign").sort(
            "prior_same_campaign"
        ),
        "Character x campaign interaction": pl.concat(
            [_interaction(train, "genre"), _interaction(train, "safety_tier")]
        ),
    }
    out.mkdir(parents=True, exist_ok=True)
    body = ["# EDA (generated by `uv run poe eda`; training split unless stated)", ""]
    for title, table in sections.items():
        body += [f"## {title}", "", _table(table), ""]
    (out / "eda.md").write_text("\n".join(body))


if __name__ == "__main__":
    run(get_settings().data_dir)
